# Channels Controller
# =================
# Channel object json:
#
# {`id`:1,
#  `type`:"Trending",
#  `default_listing`:true,
#  `category`:"undefined",
#  `title`:"Trending",
#  `thumbnail_uri`:"http://img.youtube.com/vi/cRBcP6MmE8g/0.jpg",
#  `resource_uri`:""http://api.nowmov.com/1/channels/1""}
module Aji
  class API
    version '1'
    # `http://API_HOST/1/channels`
    resource :channels do

      # ## GET channels/:channel_id
      # __Returns__ the channel with the specified id and HTTP Status Code 200
      # or 404
      #
      # __Required params__ `channel_id` unique id of the channel  
      # __Optional params__ none
      get '/:channel_id' do
        find_channel_by_id_or_error params[:channel_id]
      end

      # ## GET channels/
      # __Returns__ a list of channels matching the request parameters or all
      # channels if no parameters are specified.  
      # __Required params__ none  
      # __Optional params__
      # - `type`: The type of channel, can be `keyword`, `youtube`, `trending`,
      #   `default`, or `twitter`
      #   `keyword` channels are generated by youtube keyword searches `youtube`
      #   channels are generated by youtube video authors, and the `trending`
      #   channel is taken from the legacy Nowmov's trending videos. `default`
      #   is the standard list of channels for non-logged-in users.
      # - `keywords`: a comma separated list of keywords accompanying the
      #   `keyword` channel type.
      # - `usernames`: a comma separated list of youtube usernames for use with
      #   the `youtube` channel type.
      # - `account`: a twitter screen name for use with the twitter type.
      get do
        case params[:type]
        when 'keyword'
          kc = Channels::Keyword.find_by_keywords(
            params[:keywords].split(','))
          if kc.nil?
            kc = Channels::Keyword.create(
              :keywords => params[:keywords].split(','))
            kc.populate
          end
          kc

        when 'youtube'
          usernames = params[:usernames].split(',')
          Channels::YoutubeAccount.find_or_create_by_usernames usernames,
            :populate_if_new => true

        when 'trending'
          Channel.trending

        when 'default'
          Channel.default_listing

        when 'twitter'
          a = ExternalAccounts::Twitter.find_or_create_by_username(
            params[:account])
          Channels::TwitterAccount.find_or_create_by_account a

        else
          # FIXME: should be in User controller
          user = User.find_by_id params[:user_id]
          if user then user.subscribed_channels else Channel.all end
        end
      end

      post do
        channel = Channel.create(params) or creation_error!(params)
      end

      # ## GET channels/:channel_id/videos
      # __Returns__ all the videos of given channel and HTTP Status Code 200 or
      # 404  
      # __Required params__ `channel_id` unique id of the channel  
      # __Required params__ `user_id` unique id of the user  
      # __Optional params__ `limit` max. number of videos to return
      get '/:channel_id/videos' do
        channel = find_channel_by_id_or_error params[:channel_id]
        user = find_user_by_id_or_error params[:user_id]
        channel.personalized_content_videos params.merge(:user=>user)
      end

    end
  end
end
