module Aji
  module Channels
    # This channel is backed by an identity's social graph. A user who's auth'd us
    # access to their Twitter, Facebook, and Youtube feeds will see those videos
    # here. Each Account type has it's own implementation for determining content
    # consumed by that account and content generated by that account.
    # ## Definitions for Consume and Generate
    # - *consumption*: videos marked for consumption are videos that should be
    # viewed by an account based on input. With Twitter or Facebook accounts,
    # these would be videos tweeted/posted by friends or follows of that account.
    # For Youtube and Vimeo accounts, consumable content comes from channels that
    # user is subscribed to, as well as the account's "watch later" queue.
    #
    # - *generated*: videos generated by an account are those that should be seen
    # by subscribers to that account. In the case of Twitter/Facebook, these are
    # videos tweeted/posted by this account. For Youtube and Vimeo, these would
    # be videos saved to a users playlist, as well as videos that they have
    # uploaded. __It should be noted that generated content is not synonymous with
    # *produced* content. Accounts can generate content they did not produce as
    # this is all about determining what should go in the stream. For the content
    # producer the sole canonical source is the account listed as the Author of
    # that video.
    class Graph < Channel
      belongs_to :identity

      def populate
        # Mixin some stuff from Trending channel here?
      end
    end
  end
end

